### ISSUE TITLE
Calling DROP_SELECTED_WEAPON multiple times causes VizDoom to crash

### ISSUE THREAD

**Issue by ppaquette** [Marqt/ViZDoom#93]
Calling DROP_SELECTED_WEAPON when the weapon has already been dropped causes VizDoom to crash.

[vizdoom-crash.txt](https://github.com/Marqt/ViZDoom/files/359965/vizdoom-crash.txt)

Error message:

```
*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x278

Generating vizdoom-crash.log and killing process 17080, please wait... 29   ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
sh: 1: gxmessage: not found
Traceback (most recent call last):
  File "doom.py", line 10, in <module>
    observation, reward, done, info = env.step(action)
  File "/www/ppaquette/gym/gym/core.py", line 115, in step
    observation, reward, done, info = self._step(action)
  File "/www/ppaquette/gym/gym/envs/doom/doom_env.py", line 162, in _step
    reward = self.game.make_action(list_action)
doom_py.vizdoom.ViZDoomErrorException: Controlled ViZDoom instance reported error.
```

**Comment by arpit15** [comment]
Has any progress been made on this issue? I am facing the problem even after applying the commit.
I am obtaining 0.0 reward when using the deathmatch environment only even after being hit the enemy. I can see the health decreasing with reward returned as 0.0 only

**Comment by Marqt** [comment]
Fixed
