### ISSUE TITLE
Unable to run multiple instances on Windows

### ISSUE THREAD

**Issue by delallea** [Marqt/ViZDoom#97]
Issue found during the nucl.ai workshop, affects ticrate.py and multiple_instances.py:

````
(root) C:\tmp\ViZDoom-master\examples\python>python ticrate.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Anaconda2\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "c:\Anaconda2\lib\multiprocessing\forking.py", line 509, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\tmp\ViZDoom-master\examples\python\ticrate.py", line 52, in <module>
    p1.start()
  File "c:\Anaconda2\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "c:\Anaconda2\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "c:\Anaconda2\lib\multiprocessing\forking.py", line 358, in get_command_l
ine
    is not going to be frozen to produce a Windows executable.''')
RuntimeError:
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
````

**Comment by Marqt** [comment]
Replace the last lines of those examples for this lines:
```
if __name__ == '__main__':
    p1 = Process(target = player1)
    p1.start()
    player2()
```
and it should work.

**Comment by wjaskowski** [comment]
We need to fix the examples then.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by delallea** [comment]
Thanks Marqt, that works! I'll submit a pull request
